///////////////////////////////////////////////////////////
//  De.cs
//  Implementation of the Class De
//  Generated by Enterprise Architect
//  Created on:      09-juil.-2021 09:33:25
//  Original author: Stagiaire
///////////////////////////////////////////////////////////




namespace System {
	public class De {

		private int face;



		~De(){

		}

		public virtual void Dispose(){

		}

		public De(){

		}

		public int face{
			get{
				return face;
			}
		}

		public void Jeter(){

		}

	}//end De

}//end namespace System